version: '3'

services:
  app:
    build: .
    container_name: GH32
    volumes:
      - .:/gh32
    working_dir: /gh32
    networks:
      - webnet
    depends_on:
      - db
    command: ["conda", "run", "-n", "GH32", "bash", "-c", "python create_db.py && cd CLEAN/app/ && python CLEAN_infer_fasta.py --fasta_data gh32 && cd /gh32 && python ec_clean.py"]

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - webnet

networks:
  webnet:

volumes:
  mongo-data:
