services:
  app:
    build: .
    container_name: GH32
    volumes:
      - .:/gh32
    working_dir: /gh32
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - webnet

networks:
  webnet:

volumes:
  mongo-data:
