name: GH32
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - pandas=2.2.1
  - pymongo=4.6.3
  - requests=2.32.2
  - biopython=1.78
  - urllib3=2.2.1
  - plotly==5.22.0
  - openssl==3.0.13
  - numpy==1.26.4
  - plotly::python-kaleido
  - pytorch==2.3.1
  - torchvision==0.18.1
  - torchaudio==2.3.1